name       : python-jellyfish
version    : 0.8.9
release    : 7
source     :
    - https://pypi.io/packages/source/j/jellyfish/jellyfish-0.8.9.tar.gz : 90d25e8f5971ebbcf56f216ff5bb65d6466572b78908c88c47ab588d4ea436c2
license    : BSD-2-Clause
component  : programming.python
summary    : A python library for doing approximate and phonetic matching of strings.
description: |
    Jellyfish is a python library for doing approximate and phonetic matching of strings.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
