name       : python-jellyfish
version    : 0.7.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/69/9f/ae6f6ad509725b71d45bb408953c850da7a2ecc3dbdad4063a825702ba29/jellyfish-0.7.1.tar.gz : 79a5640bb47120596c91b9030ed3164cc5a3d0bb6b15779bb82c3c21f8efa1c1
license    : BSD-2-Clause
component  : programming.python
summary    : A python library for doing approximate and phonetic matching of strings.
description: |
    Jellyfish is a python library for doing approximate and phonetic matching of strings.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
