name       : python-jellyfish
version    : 0.5.6
release    : 1
source     :
    - https://pypi.python.org/packages/94/48/ddb1458d966f0a84e472d059d87a9d1527df7768a725132fc1d810728386/jellyfish-0.5.6.tar.gz : 887a9a49d0caee913a883c3e7eb185f6260ebe2137562365be422d1316bd39c9
license    : BSD-2-Clause
component  : programming.python
summary    : A python library for doing approximate and phonetic matching of strings.
description: |
    Jellyfish is a python library for doing approximate and phonetic matching of strings.
builddeps  :
    - pkgconfig(python)
    - pkgconfig(python-3.5)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
