name       : python-jellyfish
version    : 0.9.0
release    : 9
source     :
    - https://pypi.io/packages/source/j/jellyfish/jellyfish-0.9.0.tar.gz : 40c9a2ffd8bd3016f7611d424120442f627f56d518a106847dc93f0ead6ad79a
homepage   : https://jamesturk.github.io/jellyfish/
license    : BSD-2-Clause
component  : programming.python
summary    : A python library for doing approximate and phonetic matching of strings
description: |
    Jellyfish is a python library for doing approximate and phonetic matching of strings.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
